name: Release
on: 
  push:
    tags: 
      - '*'

jobs:
  deploy:
    name: Publish for ${{ matrix.os }}
    needs: test
    if: ${{ github.event_name == 'push' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
          linux,
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/<name>
            asset_name: <name>-linux

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --release --locked

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
